[-] testcase Test1 ()
	[-] recording
		[ ] VectorPort.Reader.Select("STIL")
		[ ] VectorPort.Writer.Select("Teradyne J750 / FLEX")
		[ ] VectorPort.DisplaySignalEditor.Uncheck()
		[ ] VectorPort.DisplaySignalEditor.Check()
		[ ] VectorPort.DisplaySignalEditor.Uncheck()
		[ ] VectorPort.DisplayTimesetEditor.Uncheck()
		[ ] VectorPort.DisplayTimesetEditor.Check()
		[ ] VectorPort.RepeatCompression.Check()
		[ ] VectorPort.RepeatCompression.Uncheck()
		[ ] VectorPort.StopConverter.Select()
		[ ] VectorPort.ClearOutput.Select()
